name: 'Notion backup'
description: 'Push notion.so asset export to github'
outputs:
  url: # output will be available to future steps
    description: 'Download url of asset export'
runs:
  using: 'node12'
  main: 'dist/index.js'
