name: 'Notion backup'
description: 'Push notion.so asset export to github'
inputs:
  notion_cookie:
    description: 'Notion cookie that is used when fetching data'
    required: true
  notion_space_id: 
    description: 'Your notion space ID'
    required: true
  notion_export_type:
    description: 'Notion Export type'
    required: true
    default: 'markdown'
outputs:
  notion_url:
    description: 'Download url of asset export'
runs:
  using: 'node12'
  main: 'dist/index.js'
