name: "Test action"
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  # unit tests
  # units:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - run: npm ci
  #   - run: npm test

  # test action works running from the graph
  use-action:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: List files on start-up 
      run: ls -al
    - name: Get notion export file
      id: notion_export
      uses: ./
      with:
        notion_cookie: ${{ secrets.NOTION_COOKIE }}
        notion_space_id: ${{ secrets.NOTION_SPACE_ID }}
    - name: Download notion export file
      run: >
        echo "${steps.notion_export.outputs.url}"
        #/usr/bin/curl -o master.zip ${steps.notion_export.outputs.url}
    - name: List files after download 
      run: ls -al